# Generated by Django 6.1.1 on 2026-10-05 20:18

import django.db.models.deletion
import queues.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('hopital', 'Hôpital'), ('centre_sante', 'Centre de santé'), ('poste_sante', 'Poste de santé'), ('clinique', 'Clinique')], default='hopital', max_length=14)),
                ('city', models.CharField(max_length=80)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QueueService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('prefix', models.CharField(default='A', max_length=2)),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('open_days', models.JSONField(default=list)),
                ('daily_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_minutes', models.PositiveSmallIntegerField(default=10)),
                ('notice_ahead', models.PositiveSmallIntegerField(default=3)),
                ('is_paused', models.BooleanField(default=False)),
                ('pause_message', models.CharField(blank=True, max_length=200)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='queues.facility')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('agent', "Agent d'accueil"), ('manager', 'Responsable')], default='agent', max_length=8)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='queues.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('facility', 'user'), name='facility_agent_unique')],
            },
        ),
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField()),
                ('number', models.PositiveIntegerField()),
                ('code', models.CharField(default=queues.models.ticket_code, max_length=12, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('lang', models.CharField(default='fr', max_length=2)),
                ('channel', models.CharField(choices=[('web', 'Site'), ('whatsapp', 'WhatsApp'), ('ussd', 'USSD'), ('desk', 'Guichet')], default='web', max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('called', 'Appelé'), ('done', 'Reçu'), ('no_show', 'Absent'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='waiting', max_length=10)),
                ('priority', models.CharField(blank=True, choices=[('', 'Aucune'), ('enceinte', 'Femme enceinte'), ('age', 'Personne âgée'), ('handicap', 'Handicap'), ('enfant', 'Jeune enfant'), ('urgence', 'Urgence')], max_length=10)),
                ('travel_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('desk', models.CharField(blank=True, max_length=30)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('recalls', models.PositiveSmallIntegerField(default=0)),
                ('soon_sent_at', models.DateTimeField(blank=True, null=True)),
                ('leave_sent_at', models.DateTimeField(blank=True, null=True)),
                ('called_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='queues.queueservice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day', 'number'],
                'indexes': [models.Index(fields=['service', 'day', 'status'], name='queue_ticket_live_idx')],
                'constraints': [models.UniqueConstraint(fields=('service', 'day', 'number'), name='queue_ticket_number_unique')],
            },
        ),
    ]
