# Generated by Django 6.1.1 on 2026-09-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpcode_alter_user_options_user_phone_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('fr', 'Français'), ('wo', 'Wolof'), ('en', 'English')], default='fr', max_length=2),
        ),
    ]
