# Generated by Django 6.1.1 on 2026-09-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_preferred_language_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='relative',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Féminin'), ('M', 'Masculin')], max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Féminin'), ('M', 'Masculin')], max_length=1),
        ),
    ]
