# Generated by Django 6.1.1 on 2026-10-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_known_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inactive_notice_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
