# Generated by Django 6.1.1 on 2026-10-05 12:52

from django.db import migrations, models


def seal_existing(apps, schema_editor):
    """Secrets de double authentification déjà enregistrés en clair : chiffrés sur place."""
    from sunusante.uploads import SEALED_PREFIX, seal_text

    TwoFactor = apps.get_model("accounts", "TwoFactor")
    for tf in TwoFactor.objects.exclude(secret__startswith=SEALED_PREFIX):
        TwoFactor.objects.filter(pk=tf.pk).update(secret=seal_text(tf.secret))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_inactive_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactor',
            name='secret',
            field=models.CharField(max_length=255),
        ),
        migrations.RunPython(seal_existing, migrations.RunPython.noop),
    ]
