/**
 * Libellés de la fiche d'urgence en français, wolof et anglais (la page des secours change de langue d'un
 * geste). Wolof à faire relire par un locuteur natif.
 */
export type EmergencyLang = "fr" | "wo" | "en";

export const FLAG_LABELS: Record<string, Record<EmergencyLang, string>> = {
  insuline: {
    fr: "Diabétique sous insuline",
    wo: "Am na diabet, di jël insilin",
    en: "Diabetic on insulin",
  },
  diabete: { fr: "Diabétique", wo: "Am na diabet (sukar)", en: "Diabetic" },
  epilepsie: { fr: "Épileptique", wo: "Am na epilepsi (xiir)", en: "Epileptic" },
  drepanocytose: { fr: "Drépanocytaire", wo: "Am na drepanositoos", en: "Sickle cell disease" },
  anticoagulant: {
    fr: "Sous anticoagulant : risque de saignement",
    wo: "Di jël garab bu tey deret : deret mën na tuuru bu bare",
    en: "On anticoagulants: bleeding risk",
  },
  cardiaque: { fr: "Maladie du cœur", wo: "Feebaru xol", en: "Heart disease" },
  hypertension: { fr: "Hypertension", wo: "Tansioŋ bu kawe", en: "High blood pressure" },
  asthme: { fr: "Asthmatique", wo: "Am na asma", en: "Asthmatic" },
  dialyse: {
    fr: "Dialysé / reins malades",
    wo: "Dañ koy dialis / feebaru wanq",
    en: "On dialysis / kidney disease",
  },
  allergie_grave: {
    fr: "Allergie grave : risque de choc",
    wo: "Alersi bu metti : mën na daanu",
    en: "Severe allergy: anaphylaxis risk",
  },
  hemophilie: { fr: "Hémophile", wo: "Am na emofili", en: "Haemophilia" },
  enceinte: { fr: "Enceinte", wo: "Dafa ëmb", en: "Pregnant" },
  memoire: { fr: "Troubles de la mémoire", wo: "Xel mi dafay fàtte", en: "Memory problems" },
  handicap: {
    fr: "Handicap (voir la note)",
    wo: "Am na lago (xoolal note bi)",
    en: "Disability (see note)",
  },
};

export const UI: Record<EmergencyLang, Record<string, string>> = {
  fr: {
    title: "Fiche d'urgence",
    samu: "Appeler le SAMU : 1515",
    pompiers: "Pompiers : 18",
    police: "Police : 17",
    alerts: "Alertes vitales",
    blood: "Groupe sanguin",
    allergies: "Allergies",
    noAllergy: "Aucune allergie connue indiquée",
    treatments: "Traitements en cours",
    conditions: "Antécédents et maladies",
    devices: "Appareils médicaux",
    notes: "Note pour les secours",
    contacts: "Personnes à prévenir",
    call: "Appeler",
    position: "Envoyer la position",
    doctor: "Médecin traitant",
    insurance: "Assurance",
    member: "N° d'adhérent",
    weight: "Poids",
    years: "ans",
    summary: "Résumé médical (médecins)",
    consults: "Dernières consultations",
    prescriptions: "Ordonnances en cours",
    stale: "Fiche non mise à jour depuis plus d'un an : à vérifier.",
    woman: "femme",
    man: "homme",
    notProvided: "Non renseigné",
    missing: "Cette fiche d'urgence n'existe pas ou a été désactivée par son titulaire.",
    footer:
      "Informations déclarées par la personne ou sa famille, mises à jour le {date}. Elles ne remplacent pas l'examen médical. Fiche fournie par Fajma ; chaque consultation est enregistrée et la famille est prévenue.",
  },
  wo: {
    title: "Kayitu musiba",
    samu: "Woo SAMU : 1515",
    pompiers: "Sapër-pompiye : 18",
    police: "Polis : 17",
    alerts: "Xibaar yu am solo",
    blood: "Xeetu deret",
    allergies: "Alersi",
    noAllergy: "Amul alersi bu ñu xam",
    treatments: "Garab yi muy jël",
    conditions: "Feebar yi mu am",
    devices: "Masin yu fajkat",
    notes: "Xibaar ngir ñi ñëw dimbali",
    contacts: "Ñi ñuy woo",
    call: "Woo",
    position: "Yónne fi nga nekk",
    doctor: "Doktoor bi koy topp",
    insurance: "Asiraans",
    member: "Nimero",
    weight: "Diisaay",
    years: "at",
    summary: "Li doktoor yi bind",
    consults: "Seetlu yu mujj yi",
    prescriptions: "Ordonaas yi muy topp",
    stale: "Yeesaluñu kayit bi lu ëpp benn at : seetal ko.",
    woman: "jigéen",
    man: "góor",
    notProvided: "Bindu ñu ko",
    missing: "Kayit bii amul walla ñu tëj ko.",
    footer:
      "Xibaar yi moom walla njabootam ñoo leen bind, ñu yeesal leen {date}. Duñu wuutu saytu doktoor. Fajma moo joxe kayit bi.",
  },
  en: {
    title: "Emergency card",
    samu: "Call the ambulance (SAMU): 1515",
    pompiers: "Fire brigade: 18",
    police: "Police: 17",
    alerts: "Critical alerts",
    blood: "Blood type",
    allergies: "Allergies",
    noAllergy: "No known allergy reported",
    treatments: "Current treatments",
    conditions: "Medical history",
    devices: "Medical devices",
    notes: "Note for rescuers",
    contacts: "Emergency contacts",
    call: "Call",
    position: "Send location",
    doctor: "Regular doctor",
    insurance: "Insurance",
    member: "Member no.",
    weight: "Weight",
    years: "years old",
    summary: "Medical summary (doctors)",
    consults: "Recent consultations",
    prescriptions: "Current prescriptions",
    stale: "Card not updated for over a year: please double-check.",
    woman: "female",
    man: "male",
    notProvided: "Not provided",
    missing: "This emergency card does not exist or has been disabled by its owner.",
    footer:
      "Information provided by the person or their family, updated on {date}. It does not replace a medical examination. Card provided by Fajma; each view is recorded and the family is notified.",
  },
};
