# Generated by Django 6.1.1 on 2026-09-29 02:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_otpcode_alter_user_options_user_phone_verified_and_more'),
        ('directory', '0003_doctor_latitude_doctor_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_period', models.DateField(help_text='Premier jour des dernières règles')),
                ('status', models.CharField(choices=[('active', 'En cours'), ('ended', 'Terminée')], default='active', max_length=10)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.relative')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_period'],
            },
        ),
        migrations.CreateModel(
            name='PrenatalVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.PositiveSmallIntegerField()),
                ('done_on', models.DateField(blank=True, null=True)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='carnet.pregnancy')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineDose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccine_code', models.CharField(max_length=20)),
                ('given_on', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_doses', to=settings.AUTH_USER_MODEL)),
                ('recorded_by_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.doctor')),
                ('relative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_doses', to='accounts.relative')),
            ],
            options={
                'ordering': ['given_on'],
            },
        ),
        migrations.CreateModel(
            name='VaccineReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccine_code', models.CharField(max_length=20)),
                ('relative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.relative')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pregnancy',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('owner',), name='one_active_pregnancy'),
        ),
        migrations.AddConstraint(
            model_name='prenatalvisit',
            constraint=models.UniqueConstraint(fields=('pregnancy', 'contact'), name='one_visit_per_contact'),
        ),
        migrations.AddConstraint(
            model_name='vaccinedose',
            constraint=models.UniqueConstraint(fields=('owner', 'relative', 'vaccine_code'), name='one_dose_per_code'),
        ),
        migrations.AddConstraint(
            model_name='vaccinedose',
            constraint=models.UniqueConstraint(condition=models.Q(('relative__isnull', True)), fields=('owner', 'vaccine_code'), name='one_dose_per_code_self'),
        ),
        migrations.AddConstraint(
            model_name='vaccinereminder',
            constraint=models.UniqueConstraint(fields=('relative', 'vaccine_code'), name='one_vaccine_reminder'),
        ),
    ]
