# Generated by Django 6.1.1 on 2026-09-28 20:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_phone', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('kind', models.CharField(choices=[('reminder_24h', 'Rappel 24 h'), ('reminder_2h', 'Rappel 2 h')], max_length=15)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('delivered', 'Livré'), ('failed', 'Échec')], default='pending', max_length=10)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='sms', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('provider_sid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('last_error', models.TextField(blank=True)),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='appointments.appointment')),
            ],
            options={
                'ordering': ['-scheduled_for'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='notificatio_status_376b6c_idx')],
                'constraints': [models.UniqueConstraint(fields=('appointment', 'kind'), name='unique_reminder_kind')],
            },
        ),
    ]
