# Generated by Django 6.1.1 on 2026-10-05 00:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsOptOut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('source', models.CharField(choices=[('sms', 'Réponse STOP par SMS'), ('whatsapp', 'STOP sur WhatsApp'), ('carrier', "Désinscrit chez l'opérateur")], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='smsreminder',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('sending', "En cours d'envoi"), ('sent', 'Envoyé'), ('delivered', 'Livré'), ('failed', 'Échec')], default='pending', max_length=10),
        ),
    ]
