# Generated by Django 6.1.1 on 2026-10-06 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience', models.CharField(choices=[('doctors', 'Médecins'), ('pharmacies', 'Pharmacies'), ('labs', 'Laboratoires'), ('clinics', 'Cliniques et secrétariats'), ('relais', 'Relais communautaires'), ('patients', 'Patients'), ('all', 'Tous les utilisateurs')], max_length=10)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(max_length=600)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('sms', models.BooleanField(default=False)),
                ('email', models.BooleanField(default=False)),
                ('recipients', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=40, unique=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('superadmin', 'Super-administrateur (tout)'), ('validation', 'Validations (professionnels, justificatifs, réseau)'), ('support', "Support (comptes, demandes d'aide, avis, SMS)"), ('finance', 'Finances (virements, remboursements)'), ('sante', 'Santé publique (veille, déclarations)'), ('communication', 'Communication (annonces, partenaires, campagnes)')], max_length=14)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
