# Generated by Django 6.1.1 on 2026-09-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='arrived_at',
            field=models.DateTimeField(blank=True, help_text="Patient arrivé en salle d'attente", null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('doctor', 'Médecin'), ('clinic', 'Secrétariat')], max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('completed', 'Terminé'), ('no_show', 'Absent')], db_index=True, default='pending', max_length=10),
        ),
    ]
