# Generated by Django 6.1.1 on 2026-09-29 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_arrived_at_appointment_cancel_reason_and_more'),
        ('directory', '0003_doctor_latitude_doctor_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='directory.doctorlocation'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='video_started_at',
            field=models.DateTimeField(blank=True, help_text='Le médecin a ouvert la téléconsultation', null=True),
        ),
    ]
