# Generated by Django 6.1.1 on 2026-09-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_postgres_no_overlap'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='coverage_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='insurance_member_number',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
