# Generated by Django 6.1.1 on 2026-09-29 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_coverage_percent_and_more'),
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='insurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='insurance.insurer'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_share',
            field=models.PositiveIntegerField(blank=True, help_text='Tiers payant : montant réglé par le patient', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tiers_payant',
            field=models.BooleanField(default=False),
        ),
    ]
