# Generated by Django 6.1.1 on 2026-09-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_insurer_appointment_patient_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='appointment',
            name='questionnaire',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
