# Generated by Django 6.1.1 on 2026-09-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_answered_at_appointment_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='channel',
            field=models.CharField(choices=[('web', 'Site / application'), ('whatsapp', 'WhatsApp'), ('ussd', 'USSD'), ('clinic', 'Secrétariat')], default='web', max_length=10),
        ),
    ]
