# Generated by Django 6.1.1 on 2026-09-29 22:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_channel'),
        ('directory', '0009_consultationtype_series_max_doctor_home_visit_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_appointments', to='directory.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='series_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='visit_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='appointment',
            name='visit_landmark',
            field=models.CharField(blank=True, help_text='Repère : « derrière la mosquée », « portail bleu »…', max_length=200),
        ),
        migrations.AddField(
            model_name='appointment',
            name='visit_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='visit_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='mode',
            field=models.CharField(choices=[('in_person', 'Cabinet'), ('teleconsultation', 'Téléconsultation'), ('home_visit', 'À domicile')], default='in_person', max_length=20),
        ),
        migrations.CreateModel(
            name='AppointmentSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interval_days', models.PositiveSmallIntegerField(default=7)),
                ('requested_count', models.PositiveSmallIntegerField()),
                ('booked_count', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_series', to='directory.doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_series', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.appointmentseries'),
        ),
    ]
