# Generated by Django 6.1.1 on 2026-10-05 00:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_practitioner_appointment_series_index_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('created', 'Rendez-vous pris'), ('confirmed', 'Confirmé'), ('rescheduled', 'Déplacé'), ('cancelled', 'Annulé'), ('completed', 'Consultation terminée'), ('no_show', 'Patient absent'), ('arrived', 'Patient arrivé'), ('status', 'Statut modifié')], max_length=12)),
                ('from_status', models.CharField(blank=True, max_length=10)),
                ('to_status', models.CharField(blank=True, max_length=10)),
                ('from_at', models.DateTimeField(blank=True, null=True)),
                ('to_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='appointments.appointment')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['appointment', 'created_at'], name='appointment_appoint_f6bb87_idx')],
            },
        ),
    ]
