# Generated by Django 6.1.1 on 2026-10-05 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_inactive_notice'),
        ('appointments', '0012_protect_medical_and_financial_records'),
        ('directory', '0011_locate_existing_doctors'),
        ('insurance', '0002_seed_insurers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['created_at'], name='appointment_created_idx'),
        ),
    ]
