# Generated by Django 6.1.1 on 2026-10-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_activity_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='mode',
            field=models.CharField(choices=[('in_person', 'Cabinet'), ('teleconsultation', 'Téléconsultation'), ('home_visit', 'À domicile'), ('async', 'Avis écrit')], default='in_person', max_length=20),
        ),
    ]
