# Generated by Django 6.1.1 on 2026-10-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_alter_appointment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='late_cancellation',
            field=models.BooleanField(default=False),
        ),
    ]
