# Generated by Django 6.1.1 on 2026-10-06 11:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0014_alter_appointment_mode'),
        ('directory', '0013_credentials_for_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField(default=5000)),
                ('response_hours', models.PositiveSmallIntegerField(default=24)),
                ('instructions', models.CharField(blank=True, max_length=400)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='async_offer', to='directory.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AsyncRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('awaiting_payment', 'En attente de paiement'), ('submitted', 'Envoyée au médecin'), ('answered', 'Réponse reçue'), ('expired', 'Sans réponse : remboursée'), ('cancelled', 'Annulée')], default='awaiting_payment', max_length=16)),
                ('symptoms', models.TextField(max_length=3000)),
                ('since', models.CharField(blank=True, max_length=80)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('current_treatments', models.CharField(blank=True, max_length=500)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, max_length=4000)),
                ('outcome', models.CharField(blank=True, choices=[('advice', 'Conseils'), ('prescription', 'Ordonnance'), ('in_person', 'Consultation en personne conseillée'), ('emergency', 'Urgence : consulter immédiatement')], max_length=12)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='async_request', to='appointments.appointment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'deadline_at'], name='async_deadline_idx')],
            },
        ),
    ]
