# Generated by Django 6.1.1 on 2026-09-28 21:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='accepts_new_patients',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='auto_confirm',
            field=models.BooleanField(default=False, help_text='Confirme automatiquement les RDV pris en ligne'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='booking_horizon_days',
            field=models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='doctor',
            name='booking_instructions',
            field=models.TextField(blank=True, help_text='Consignes affichées au patient avant le RDV', max_length=1000),
        ),
        migrations.AddField(
            model_name='doctor',
            name='cancellation_deadline_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text="0 = annulation en ligne possible jusqu'au dernier moment", validators=[django.core.validators.MaxValueValidator(168)]),
        ),
        migrations.AddField(
            model_name='doctor',
            name='min_notice_hours',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(168)]),
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='directory.doctor')),
            ],
            options={
                'ordering': ['starts_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='time_off_end_after_start')],
            },
        ),
    ]
