# Generated by Django 6.1.1 on 2026-09-29 00:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_doctor_accepts_new_patients_doctor_auto_confirm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='teleconsultation_prepayment',
            field=models.BooleanField(default=False, help_text='Paiement en ligne exigé avant une téléconsultation'),
        ),
        migrations.CreateModel(
            name='DoctorLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=80)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='directory.doctor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='directory.doctorlocation'),
        ),
    ]
