# Generated by Django 6.1.1 on 2026-09-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_doctor_latitude_doctor_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationtype',
            name='questionnaire',
            field=models.JSONField(blank=True, default=list, help_text='Remplace le questionnaire par défaut du médecin'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='questionnaire',
            field=models.JSONField(blank=True, default=list, help_text='Questions posées au patient avant la consultation'),
        ),
    ]
