# Generated by Django 6.1.1 on 2026-09-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_consultationtype_questionnaire_doctor_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='doctor_reply',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='report_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='review',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('published', 'Publié'), ('reported', 'Signalé'), ('hidden', 'Masqué')], default='published', max_length=10),
        ),
    ]
