# Generated by Django 6.1.1 on 2026-09-29 13:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_review_doctor_reply_review_moderated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('ordre', "Inscription à l'Ordre des médecins"), ('diplome', 'Diplôme de médecine / spécialité'), ('identite', "Pièce d'identité"), ('autre', 'Autre justificatif')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('file_path', models.CharField(max_length=300)),
                ('mime_type', models.CharField(max_length=60)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En cours de vérification'), ('accepted', 'Accepté'), ('rejected', 'Refusé')], default='pending', max_length=10)),
                ('review_note', models.CharField(blank=True, max_length=300)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='directory.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
