# Generated by Django 6.1.1 on 2026-09-29 15:11

import directory.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_doctorcredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed_token', models.CharField(default=directory.models.new_feed_token, max_length=64, unique=True)),
                ('import_url', models.URLField(blank=True, max_length=1000)),
                ('last_import_at', models.DateTimeField(blank=True, null=True)),
                ('last_import_error', models.CharField(blank=True, max_length=300)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_link', to='directory.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalBusy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_busy', to='directory.doctor')),
            ],
            options={
                'indexes': [models.Index(fields=['doctor', 'ends_at'], name='directory_e_doctor__f8b0ca_idx')],
            },
        ),
    ]
