# Generated by Django 6.1.1 on 2026-09-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_calendar_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='order_number',
            field=models.CharField(blank=True, help_text="N° d'inscription à l'Ordre national des médecins du Sénégal", max_length=40),
        ),
        migrations.AddField(
            model_name='doctor',
            name='practice_name',
            field=models.CharField(blank=True, help_text="Cabinet, clinique ou hôpital d'exercice", max_length=160),
        ),
        migrations.AddField(
            model_name='doctor',
            name='practice_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='doctor',
            name='professional_title',
            field=models.CharField(blank=True, help_text='Titres et qualifications (ex. Ancien interne des hôpitaux)', max_length=160),
        ),
        migrations.AddField(
            model_name='doctor',
            name='signature_path',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='doctor',
            name='stamp_path',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
