# Generated by Django 6.1.1 on 2026-09-29 22:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_prescription_mentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationtype',
            name='series_max',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='doctor',
            name='home_visit_area',
            field=models.CharField(blank=True, help_text='Quartiers ou communes desservis', max_length=300),
        ),
        migrations.AddField(
            model_name='doctor',
            name='home_visit_fee',
            field=models.PositiveIntegerField(default=0, help_text='Supplément de déplacement ajouté au tarif'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='home_visits',
            field=models.BooleanField(default=False, help_text='Accepte les demandes de consultation à domicile'),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='kind',
            field=models.CharField(choices=[('office', 'Cabinet et vidéo'), ('home_visit', 'Visites à domicile')], default='office', max_length=10),
        ),
        migrations.AlterField(
            model_name='consultationtype',
            name='mode',
            field=models.CharField(choices=[('in_person', 'Cabinet'), ('teleconsultation', 'Vidéo'), ('both', 'Cabinet et vidéo'), ('home_visit', 'À domicile')], default='both', max_length=20),
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Proposé'), ('accepted', 'Accepté'), ('declined', 'Refusé'), ('cancelled', 'Annulé')], db_index=True, default='pending', max_length=10)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='directory.doctor')),
                ('replacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacing', to='directory.doctor')),
            ],
            options={
                'ordering': ['starts_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='replacement_end_after_start'), models.CheckConstraint(condition=models.Q(('doctor', models.F('replacement')), _negated=True), name='replacement_not_self')],
            },
        ),
    ]
