# Generated by Django 6.1.1 on 2026-09-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_consultationtype_series_max_doctor_home_visit_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo_path',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='on_duty_until',
            field=models.DateTimeField(blank=True, help_text="Fin de la garde (vide = jusqu'à nouvel ordre)", null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='open_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
