# Generated by Django 6.1.1 on 2026-09-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='kind',
            field=models.CharField(choices=[('clinic', 'Clinique / centre de santé'), ('practice', "Cabinet d'un médecin")], default='clinic', max_length=10),
        ),
    ]
