# Generated by Django 6.1.1 on 2026-10-05 20:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0006_payment_payer_alter_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('pending', "En attente d'accord"), ('active', 'Actif'), ('revoked', 'Retiré'), ('expired', 'Invitation expirée')], default='pending', max_length=8)),
                ('can_book', models.BooleanField(default=False)),
                ('can_see_records', models.BooleanField(default=False)),
                ('invite_code_hash', models.CharField(blank=True, max_length=64)),
                ('invite_expires_at', models.DateTimeField(blank=True, null=True)),
                ('invite_attempts', models.PositiveSmallIntegerField(default=0)),
                ('invites_sent', models.PositiveSmallIntegerField(default=0)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('monthly_reminder_amount', models.PositiveIntegerField(default=0)),
                ('monthly_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('low_balance_alert', models.PositiveIntegerField(default=5000)),
                ('low_balance_alerted_at', models.DateTimeField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_links_received', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_links_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTopUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué')], default='pending', max_length=8)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('provider_token', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('checkout_url', models.URLField(blank=True, max_length=500)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topups', to='family.carelink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('topup', 'Recharge'), ('spend', 'Consultation payée'), ('refund', 'Consultation annulée (recréditée)')], max_length=8)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='family.carelink')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='payments.payment')),
                ('topup', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entry', to='family.credittopup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='carelink',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'active'])), fields=('sponsor', 'beneficiary'), name='one_open_care_link'),
        ),
        migrations.AddConstraint(
            model_name='carelink',
            constraint=models.CheckConstraint(condition=models.Q(('sponsor', models.F('beneficiary')), _negated=True), name='care_link_not_self'),
        ),
        migrations.AddConstraint(
            model_name='creditentry',
            constraint=models.UniqueConstraint(condition=models.Q(('payment__isnull', False)), fields=('payment', 'kind'), name='credit_once_per_payment'),
        ),
    ]
