# Generated by Django 6.1.1 on 2026-09-30 00:41

import django.db.models.deletion
import labs.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_prescription_mentions'),
        ('appointments', '0010_appointment_practitioner_appointment_series_index_and_more'),
        ('directory', '0010_doctor_photo_path_pharmacy_on_duty_until_and_more'),
        ('medical', '0005_prescription_mentions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('city', models.CharField(max_length=80)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('opening_hours', models.CharField(blank=True, help_text="Ex. lun.–sam. 7 h 30 – 18 h, prélèvements jusqu'à 11 h", max_length=160)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'laboratories',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=labs.models.new_lab_reference, max_length=16, unique=True)),
                ('tests', models.TextField(max_length=2000)),
                ('instructions', models.CharField(blank=True, help_text='Ex. à jeun depuis 12 h', max_length=300)),
                ('urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('prescribed', 'Prescrite'), ('sent', 'Envoyée au laboratoire'), ('received', 'Prélèvement effectué'), ('completed', 'Résultats disponibles'), ('cancelled', 'Annulée')], db_index=True, default='prescribed', max_length=12)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_note', models.TextField(blank=True, max_length=2000)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='directory.doctor')),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='labs.laboratory')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to=settings.AUTH_USER_MODEL)),
                ('relative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.relative')),
                ('results', models.ManyToManyField(blank=True, related_name='lab_orders', to='medical.medicaldocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaboratoryMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='labs.laboratory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('laboratory', 'user'), name='unique_lab_member')],
            },
        ),
    ]
