# Generated by Django 6.1.1 on 2026-10-05 18:29

from django.db import migrations, models


def keep_existing_partners(apps, schema_editor):
    """Laboratoires déjà partenaires avant l'obligation de justificatifs : ils restent en ligne."""
    Laboratory = apps.get_model("labs", "Laboratory")
    Laboratory.objects.filter(members__isnull=False).update(is_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_protect_medical_and_financial_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(keep_existing_partners, migrations.RunPython.noop),
    ]
