# Generated by Django 6.1.1 on 2026-10-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_laboratory_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='kind',
            field=models.CharField(choices=[('analyses', 'Analyses médicales'), ('imagerie', 'Imagerie médicale'), ('both', 'Analyses et imagerie')], default='analyses', max_length=10),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='modalities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='laborder',
            name='contrast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laborder',
            name='kind',
            field=models.CharField(choices=[('analyses', 'Analyses'), ('imagerie', 'Imagerie')], db_index=True, default='analyses', max_length=10),
        ),
        migrations.AddField(
            model_name='laborder',
            name='modality',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
