# Generated by Django 6.1.1 on 2026-09-29 13:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0006_doctorcredential'),
        ('medical', '0004_issueddocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('open', 'En attente de réponse'), ('answered', 'Répondu'), ('closed', 'Clôturé')], default='open', max_length=10)),
                ('patient_informed_at', models.DateTimeField(blank=True, null=True)),
                ('documents', models.ManyToManyField(blank=True, related_name='expertise_requests', to='medical.medicaldocument')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise_received', to='directory.doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise_sent', to='directory.doctor')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertiseMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=5000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='directory.doctor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='expertise.expertiserequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
