# Generated by Django 6.1.1 on 2026-09-29 02:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_otpcode_alter_user_options_user_phone_verified_and_more'),
        ('directory', '0003_doctor_latitude_doctor_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('ipm', 'IPM'), ('mutuelle', 'Mutuelle de santé / CMU'), ('assurance', 'Assurance privée'), ('public', 'Programme public')], max_length=10)),
                ('default_coverage_percent', models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PatientCoverage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_number', models.CharField(max_length=40)),
                ('coverage_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coverages', to='insurance.insurer')),
                ('relative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='accounts.relative')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorInsurer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tiers_payant', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_insurers', to='directory.doctor')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='insurance.insurer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('doctor', 'insurer'), name='doctor_insurer_unique')],
            },
        ),
    ]
