# Generated by Django 6.1.1 on 2026-09-30 00:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_prescription_mentions'),
        ('medical', '0005_prescription_mentions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.CharField(max_length=160)),
                ('dosage', models.CharField(blank=True, help_text='Ex. 1 comprimé', max_length=160)),
                ('times', models.JSONField(default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('sms', models.BooleanField(default=False, help_text='Aussi par SMS/WhatsApp (sinon notification gratuite sur le téléphone)')),
                ('active', models.BooleanField(default=True)),
                ('sent_keys', models.JSONField(default=list)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_reminders', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medical.prescription')),
                ('relative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.relative')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('blood_pressure', 'Tension artérielle'), ('glucose', 'Glycémie'), ('weight', 'Poids')], max_length=15)),
                ('systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pulse', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('context', models.CharField(blank=True, choices=[('', '—'), ('fasting', 'À jeun'), ('after_meal', 'Après un repas'), ('random', 'Autre moment')], max_length=12)),
                ('measured_at', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL)),
                ('relative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='accounts.relative')),
            ],
            options={
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['patient', 'kind', 'measured_at'], name='care_measur_patient_16ea6f_idx')],
            },
        ),
    ]
