# Generated by Django 6.1.1 on 2026-10-05 00:27

from django.db import migrations, models


def number_existing(apps, schema_editor):
    """Paiements déjà encaissés : numérotés dans l'ordre chronologique d'encaissement, année par année."""
    from django.utils import timezone

    Counter = apps.get_model("payments", "ReceiptCounter")
    rows = []
    for name in ("Payment", "SubscriptionPayment"):
        model = apps.get_model("payments", name)
        rows += [(obj.paid_at or obj.created_at, model, obj.pk) for obj in model.objects.filter(status="paid", receipt_number__isnull=True)]
    for paid_at, model, pk in sorted(rows, key=lambda r: r[0]):
        year = timezone.localtime(paid_at).year
        counter, _ = Counter.objects.get_or_create(year=year)
        counter.last += 1
        counter.save()
        model.objects.filter(pk=pk).update(receipt_number=f"FJ-{year}-{counter.last:06d}")


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payout_ledgerentry_refund_subscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptCounter',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('last', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(number_existing, migrations.RunPython.noop),
    ]
