# Generated by Django 6.1.1 on 2026-10-05 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_protect_medical_and_financial_records'),
        ('payments', '0003_receipts_and_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
