# Generated by Django 6.1.1 on 2026-10-05 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_activity_indexes'),
        ('payments', '0004_protect_medical_and_financial_records'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-created_at'], name='payment_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_at'], name='payment_paid_at_idx'),
        ),
    ]
