# Generated by Django 6.1.1 on 2026-10-05 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_activity_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_for_others', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('free_money', 'Free Money'), ('cash', 'Espèces'), ('card', 'Carte bancaire ou mobile money'), ('credit', 'Crédit santé')], max_length=15),
        ),
    ]
