/** Icône d'une spécialité : le serveur envoie un nom d'icône (« HeartPulse », « Baby »…), dessiné ici.
 * Les noms viennent du catalogue backend/directory/specialties.py. */
import {
  Activity,
  Apple,
  Baby,
  Bean,
  Bone,
  Brain,
  BrainCircuit,
  Briefcase,
  Bug,
  Droplet,
  Droplets,
  Dumbbell,
  Ear,
  Eye,
  Flower2,
  Hand,
  HandHeart,
  Heart,
  HeartHandshake,
  HeartPulse,
  MessageCircleHeart,
  PersonStanding,
  Ribbon,
  Scan,
  Scissors,
  Smile,
  Soup,
  Sparkles,
  Speech,
  Stethoscope,
  Syringe,
  Venus,
  Wand2,
  Wind,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  Activity,
  Apple,
  Baby,
  Bean,
  Bone,
  Brain,
  BrainCircuit,
  Briefcase,
  Bug,
  Droplet,
  Droplets,
  Dumbbell,
  Ear,
  Eye,
  Flower2,
  Hand,
  HandHeart,
  Heart,
  HeartHandshake,
  HeartPulse,
  MessageCircleHeart,
  PersonStanding,
  Ribbon,
  Scan,
  Scissors,
  Smile,
  Soup,
  Sparkles,
  Speech,
  Stethoscope,
  Syringe,
  Venus,
  Wand2,
  Wind,
};

export function SpecialtyIcon({
  name,
  className = "size-5",
}: {
  name?: string | null;
  className?: string;
}) {
  const Icon = (name && ICONS[name]) || Stethoscope;
  return <Icon className={className} aria-hidden />;
}
