# Generated by Django 6.1.1 on 2026-10-06 12:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('assureur', 'Assurance, IPM, mutuelle'), ('operateur', 'Opérateur, paiement'), ('pharmacie', 'Pharmacie, laboratoire'), ('institution', 'Institution publique'), ('ong', 'ONG, fondation'), ('entreprise', 'Entreprise'), ('autre', 'Autre')], max_length=12)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('website', models.URLField(blank=True)),
                ('logo_path', models.CharField(blank=True, max_length=300)),
                ('logo_mime', models.CharField(blank=True, max_length=60)),
                ('is_public', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('body', models.CharField(max_length=200)),
                ('cta_label', models.CharField(default='En savoir plus', max_length=30)),
                ('cta_url', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('prevention', 'Campagne de prévention / santé publique'), ('assurance', 'Assurance, mutuelle'), ('produit', 'Produit sans ordonnance autorisé'), ('service', 'Service de santé (dépistage, laboratoire…)')], max_length=12)),
                ('placements', models.JSONField(default=list)),
                ('cities', models.JSONField(default=list)),
                ('languages', models.JSONField(default=list)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('approved', 'Validée'), ('paused', 'Suspendue')], default='draft', max_length=8)),
                ('charter_checked', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='partners.partner')),
            ],
            options={
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='CampaignStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('placement', models.CharField(max_length=10)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='partners.campaign')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('campaign', 'day', 'placement'), name='campaign_stat_unique')],
            },
        ),
    ]
