# Generated by Django 6.1.1 on 2026-10-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image_mime',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='campaign',
            name='image_path',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='campaign',
            name='theme',
            field=models.CharField(choices=[('vert', 'Vert Fajma'), ('rose', 'Rose'), ('bleu', 'Bleu'), ('orange', 'Orange'), ('violet', 'Violet'), ('rouge', 'Rouge')], default='vert', max_length=8),
        ),
    ]
