"""
Textes du menu WhatsApp / USSD, en français, wolof et anglais.
Écrans USSD : 182 caractères au plus — garder les textes courts.
Le wolof doit être relu par un locuteur natif avant la mise en production.
"""

TEXTS = {
    "fr": {
        "home": "Fajma - santé\n",
        "book": "Prendre rendez-vous",
        "queue": "Ticket hôpital (file d'attente)",
        "q_menu": "Ticket hôpital :",
        "q_take": "Prendre un ticket",
        "q_mine": "Mon ticket (ma place)",
        "q_facility": "Établissement :",
        "q_service": "Service :",
        "q_none": "Aucun établissement ne propose encore de ticket dans cette ville.",
        "q_confirm": "{service} - {facility} : {waiting} personne(s) en attente, environ {eta}. Prendre un ticket ?",
        "q_yes": "Oui, prendre un ticket",
        "q_ok": "Votre ticket : {label}. {ahead} personne(s) devant vous, environ {eta}. Un SMS vous prévient quand c'est bientôt votre tour.",
        "q_status": "Ticket {label} ({facility}) : {state}",
        "q_waiting": "{ahead} personne(s) devant vous, environ {eta}.",
        "q_called": "c'est votre tour, présentez-vous {desk}.",
        "q_closed": "Ce ticket est terminé.",
        "q_no_ticket": "Vous n'avez pas de ticket aujourd'hui.",
        "mine": "Mes rendez-vous",
        "cancel": "Annuler un RDV",
        "pharma": "Pharmacies de garde",
        "lang": "Làkk / Langue / Language",
        "invalid": "Choix invalide.\n",
        "home_opt": "00. Menu principal",
        "more": "Suite",
        "specialty": "Spécialité :",
        "city": "Ville :",
        "doctor": "Médecin (prochain créneau) :",
        "slot": "{doctor} - créneau :",
        "name": "Votre prénom et nom :",
        "confirm_q": "Confirmer le RDV avec {doctor}, {when}, {price} F ?",
        "confirm": "Confirmer",
        "abort": "Abandonner",
        "aborted": "Réservation abandonnée.",
        "sorry": "Désolé : {error}",
        "taken": "Désolé : ce créneau vient d'être pris. Recommencez avec 00.",
        "booked_ok": "RDV confirmé : {doctor}, {when}. Un SMS de rappel vous sera envoyé.",
        "booked_pending": "RDV en attente de confirmation du médecin : {doctor}, {when}. Un SMS de rappel vous sera envoyé.",
        "none_upcoming": "Aucun rendez-vous à venir.",
        "pending": " (en attente)",
        "your_appts": "Vos RDV :\n",
        "none_cancel": "Aucun rendez-vous à annuler.",
        "which_cancel": "RDV à annuler :",
        "cancel_q": "Confirmer l'annulation ?",
        "yes_cancel": "Oui, annuler",
        "no": "Non",
        "kept": "Rendez-vous conservé.",
        "already": "Ce rendez-vous est déjà annulé.",
        "too_late": "Trop tard pour annuler en ligne (moins de {h} h). Appelez le cabinet.",
        "cancelled": "Rendez-vous annulé. Le créneau est libéré.",
        "on_duty": " (garde)",
        "pharmacies": "Pharmacies {city} :\n",
        "choose_lang": "Làkk / Langue / Language :",
    },
    "wo": {
        "home": "Fajma - wér-gi-yaram\n",
        "book": "Jël ndaje",
        "queue": "Tike opitaal (toog ngir xaar)",
        "q_menu": "Tike opitaal :",
        "q_take": "Jël tike",
        "q_mine": "Sama tike (sama palaas)",
        "q_facility": "Opitaal :",
        "q_service": "Servis :",
        "q_none": "Amul benn opitaal bu joxe tike ci dëkk bii ba léegi.",
        "q_confirm": "{service} - {facility} : {waiting} nit ñoo ngi xaar, lu tollu ci {eta}. Jël tike ?",
        "q_yes": "Waaw, jël tike",
        "q_ok": "Sa tike : {label}. {ahead} nit ñoo la jiitu, lu tollu ci {eta}. SMS dina la xamal bu sa waxtu jegee.",
        "q_status": "Tike {label} ({facility}) : {state}",
        "q_waiting": "{ahead} nit ñoo la jiitu, lu tollu ci {eta}.",
        "q_called": "sa waxtu agsi na, ñëwal {desk}.",
        "q_closed": "Tike bii jeex na.",
        "q_no_ticket": "Amoo tike tey.",
        "mine": "Samay ndaje",
        "cancel": "Far ndaje",
        "pharma": "Farmasi yu gàrd",
        "lang": "Làkk / Langue / Language",
        "invalid": "Tànn bi baaxul.\n",
        "home_opt": "00. Menu bu njëkk",
        "more": "Li ci des",
        "specialty": "Xeetu doktoor :",
        "city": "Dëkk :",
        "doctor": "Doktoor (waxtu bu jëkk) :",
        "slot": "{doctor} - waxtu :",
        "name": "Sa tur ak sa sant :",
        "confirm_q": "Dëggal ndaje ak {doctor}, {when}, {price} F ?",
        "confirm": "Dëggal",
        "abort": "Bàyyi",
        "aborted": "Bàyyi nga ndaje bi.",
        "sorry": "Baal ma : {error}",
        "taken": "Baal ma : waxtu bi ñu jël ko léegi. Tàmbaliwaat ak 00.",
        "booked_ok": "Ndaje bi dëggal nañu ko : {doctor}, {when}. Dinañu la yónne SMS ngir fàttali la.",
        "booked_pending": "Ndaje bi mi ngi xaar doktoor bi dëggal ko : {doctor}, {when}. Dinañu la yónne SMS.",
        "none_upcoming": "Amoo benn ndaje buy ñëw.",
        "pending": " (mi ngi xaar)",
        "your_appts": "Say ndaje :\n",
        "none_cancel": "Amoo benn ndaje boo mën a far.",
        "which_cancel": "Ndaje bi ngay far :",
        "cancel_q": "Dëggal far bi ?",
        "yes_cancel": "Waaw, far ko",
        "no": "Déedéet",
        "kept": "Ndaje bi mi ngi fi.",
        "already": "Ndaje bii far nañu ko ba noppi.",
        "too_late": "Dafa yéex ngir far ci internet (lu yées {h} waxtu). Wooal kabine bi.",
        "cancelled": "Far nañu ndaje bi. Waxtu bi ubbeeku na.",
        "on_duty": " (gàrd)",
        "pharmacies": "Farmasi yi ci {city} :\n",
        "choose_lang": "Làkk / Langue / Language :",
    },
    "en": {
        "home": "Fajma - health\n",
        "book": "Book an appointment",
        "queue": "Hospital ticket (queue)",
        "q_menu": "Hospital ticket:",
        "q_take": "Take a ticket",
        "q_mine": "My ticket (my place)",
        "q_facility": "Facility:",
        "q_service": "Service:",
        "q_none": "No facility offers tickets in this city yet.",
        "q_confirm": "{service} - {facility}: {waiting} person(s) waiting, about {eta}. Take a ticket?",
        "q_yes": "Yes, take a ticket",
        "q_ok": "Your ticket: {label}. {ahead} person(s) ahead of you, about {eta}. An SMS will tell you when your turn is near.",
        "q_status": "Ticket {label} ({facility}): {state}",
        "q_waiting": "{ahead} person(s) ahead of you, about {eta}.",
        "q_called": "it's your turn, please go {desk}.",
        "q_closed": "This ticket is finished.",
        "q_no_ticket": "You have no ticket today.",
        "mine": "My appointments",
        "cancel": "Cancel an appointment",
        "pharma": "On-duty pharmacies",
        "lang": "Làkk / Langue / Language",
        "invalid": "Invalid choice.\n",
        "home_opt": "00. Main menu",
        "more": "More",
        "specialty": "Specialty:",
        "city": "City:",
        "doctor": "Doctor (next slot):",
        "slot": "{doctor} - slot:",
        "name": "Your first and last name:",
        "confirm_q": "Confirm appointment with {doctor}, {when}, {price} F?",
        "confirm": "Confirm",
        "abort": "Cancel",
        "aborted": "Booking cancelled.",
        "sorry": "Sorry: {error}",
        "taken": "Sorry: this slot was just taken. Start again with 00.",
        "booked_ok": "Appointment confirmed: {doctor}, {when}. You will get an SMS reminder.",
        "booked_pending": "Appointment awaiting the doctor's confirmation: {doctor}, {when}. You will get an SMS reminder.",
        "none_upcoming": "No upcoming appointments.",
        "pending": " (pending)",
        "your_appts": "Your appointments:\n",
        "none_cancel": "No appointment to cancel.",
        "which_cancel": "Appointment to cancel:",
        "cancel_q": "Confirm cancellation?",
        "yes_cancel": "Yes, cancel",
        "no": "No",
        "kept": "Appointment kept.",
        "already": "This appointment is already cancelled.",
        "too_late": "Too late to cancel online (less than {h} h). Please call the practice.",
        "cancelled": "Appointment cancelled. The slot is now free.",
        "on_duty": " (on duty)",
        "pharmacies": "Pharmacies in {city}:\n",
        "choose_lang": "Làkk / Langue / Language:",
    },
}

LANG_OPTIONS = [("fr", "Français"), ("wo", "Wolof"), ("en", "English")]
