# Generated by Django 6.1.1 on 2026-09-30 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('contact', models.CharField(max_length=254)),
                ('topic', models.CharField(choices=[('compte', 'Connexion et compte'), ('rdv', 'Rendez-vous'), ('paiement', 'Paiement et remboursement'), ('ordonnance', 'Ordonnances et documents'), ('pro', 'Espace professionnel'), ('donnees', 'Mes données personnelles'), ('autre', 'Autre question')], max_length=12)),
                ('message', models.TextField(max_length=3000)),
                ('status', models.CharField(choices=[('open', 'À traiter'), ('closed', 'Traitée')], default='open', max_length=6)),
                ('admin_note', models.CharField(blank=True, max_length=500)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
