# Generated by Django 6.1.1 on 2026-09-29 02:58

import django.db.models.deletion
import medical.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpcode_alter_user_options_user_phone_verified_and_more'),
        ('appointments', '0008_appointment_answered_at_appointment_answers_and_more'),
        ('directory', '0004_consultationtype_questionnaire_doctor_questionnaire'),
        ('medical', '0003_patientrecall_documentshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('certificat', 'Certificat médical'), ('arret_travail', "Avis d'arrêt de travail"), ('aptitude', "Certificat d'aptitude au sport"), ('courrier', 'Courrier à un confrère')], max_length=15)),
                ('body', models.TextField(blank=True, max_length=4000)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('recipient', models.CharField(blank=True, max_length=120)),
                ('reference', models.CharField(default=medical.models.new_document_reference, max_length=20, unique=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_documents', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_documents', to='directory.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_documents', to=settings.AUTH_USER_MODEL)),
                ('relative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.relative')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
