# Generated by Django 6.1.1 on 2026-09-29 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_prescription_mentions'),
        ('medical', '0004_issueddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueddocument',
            name='issuer',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='prescription',
            name='issuer',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='prescription',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='prescription',
            name='relative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.relative'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='renewals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
