# Generated by Django 6.1.1 on 2026-09-30 23:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_locate_existing_doctors'),
        ('medical', '0005_prescription_mentions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='alert_doctors',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='emergency_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='emergency_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='emergency_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='renewal_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PrescriptionRenewal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Renouvelée'), ('refused', 'Refusée'), ('cancelled', 'Annulée')], default='pending', max_length=10)),
                ('patient_note', models.CharField(blank=True, max_length=500)),
                ('doctor_reply', models.CharField(blank=True, max_length=500)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests', to='directory.doctor')),
                ('new_prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medical.prescription')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests', to='medical.prescription')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('prescription',), name='one_pending_renewal')],
            },
        ),
    ]
