# Generated by Django 6.1.1 on 2026-10-06 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_protect_medical_and_financial_records'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='condition_code',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='condition_status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='test_result',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='DiseaseNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition_code', models.CharField(max_length=30)),
                ('condition_status', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('declared_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('declared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='medical.medicalrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
