# Generated by Django 6.1.1 on 2026-10-06 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_pending_email'),
        ('medical', '0008_medicalrecord_condition_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='critical_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='emergency_contacts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='medical_devices',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='rescuer_notes',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='RelativeEmergencyCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('allergies', models.TextField(blank=True, max_length=2000)),
                ('conditions', models.TextField(blank=True, max_length=2000)),
                ('treatments', models.TextField(blank=True, max_length=2000)),
                ('critical_flags', models.JSONField(blank=True, default=list)),
                ('emergency_contacts', models.JSONField(blank=True, default=list)),
                ('medical_devices', models.CharField(blank=True, max_length=300)),
                ('rescuer_notes', models.CharField(blank=True, max_length=300)),
                ('relative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_card', to='accounts.relative')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
