# Generated by Django 6.1.1 on 2026-10-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_emergency_card_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='emergency_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relativeemergencycard',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
