# Generated by Django 6.1.1 on 2026-10-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_emergency_summary_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='safety',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
