# Generated by Django 6.1.1 on 2026-10-06 12:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_user_pending_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.CharField(max_length=160)),
                ('area', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('max_people', models.PositiveSmallIntegerField(default=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('village', models.CharField(blank=True, max_length=120)),
                ('consent', models.CharField(choices=[('oral', 'Accord oral (devant témoin)'), ('signed', 'Formulaire signé'), ('guardian', 'Accord du tuteur ou parent')], max_length=10)),
                ('consent_witness', models.CharField(blank=True, max_length=120)),
                ('consent_at', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Suivi'), ('transferred', 'Dossier transféré à la personne'), ('ended', 'Suivi arrêté')], default='active', max_length=12)),
                ('transfer_code_hash', models.CharField(blank=True, max_length=64)),
                ('transfer_phone', models.CharField(blank=True, max_length=20)),
                ('transfer_expires_at', models.DateTimeField(blank=True, null=True)),
                ('transfer_attempts', models.PositiveSmallIntegerField(default=0)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follows', to='community.communityagent')),
                ('relative', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_follow', to='accounts.relative')),
                ('transferred_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
