# Generated by Django 6.1.1 on 2026-09-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment_mime',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_path',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
