/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AideRouteImport } from './routes/aide'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ConfirmerEmailRouteImport } from './routes/confirmer-email'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as PharmaciesRouteImport } from './routes/pharmacies'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCliniqueRouteImport } from './routes/_authenticated/clinique'
import { Route as AuthenticatedDossierRouteImport } from './routes/_authenticated/dossier'
import { Route as AuthenticatedExpertiseRouteImport } from './routes/_authenticated/expertise'
import { Route as AuthenticatedLaboratoireRouteImport } from './routes/_authenticated/laboratoire'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMonEspaceRouteImport } from './routes/_authenticated/mon-espace'
import { Route as AuthenticatedPharmacieRouteImport } from './routes/_authenticated/pharmacie'
import { Route as AuthenticatedProRouteImport } from './routes/_authenticated/pro'
import { Route as AuthenticatedSecuriteRouteImport } from './routes/_authenticated/securite'
import { Route as CliniquesIndexRouteImport } from './routes/cliniques.index'
import { Route as CliniquesIdRouteImport } from './routes/cliniques.$id'
import { Route as MedecinsIndexRouteImport } from './routes/medecins/index'
import { Route as MedecinsIdRouteImport } from './routes/medecins/$id'
import { Route as SpecialitesIndexRouteImport } from './routes/specialites.index'
import { Route as SpecialitesSlugRouteImport } from './routes/specialites.$slug'
import { Route as UrgenceTokenRouteImport } from './routes/urgence.$token'
import { Route as VerifierReferenceRouteImport } from './routes/verifier.$reference'
import { Route as WidgetDoctorIdRouteImport } from './routes/widget.$doctorId'
import { Route as AuthenticatedOrdonnanceIdRouteImport } from './routes/_authenticated/ordonnance.$id'
import { Route as AuthenticatedPaiementRetourRouteImport } from './routes/_authenticated/paiement.retour'
import { Route as AuthenticatedPatientsIdRouteImport } from './routes/_authenticated/patients.$id'
import { Route as AuthenticatedTeleconsultationIdRouteImport } from './routes/_authenticated/teleconsultation.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmerEmailRoute = ConfirmerEmailRouteImport.update({
  id: '/confirmer-email',
  path: '/confirmer-email',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmaciesRoute = PharmaciesRouteImport.update({
  id: '/pharmacies',
  path: '/pharmacies',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCliniqueRoute = AuthenticatedCliniqueRouteImport.update({
  id: '/clinique',
  path: '/clinique',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDossierRoute = AuthenticatedDossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpertiseRoute = AuthenticatedExpertiseRouteImport.update({
  id: '/expertise',
  path: '/expertise',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLaboratoireRoute =
  AuthenticatedLaboratoireRouteImport.update({
    id: '/laboratoire',
    path: '/laboratoire',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonEspaceRoute = AuthenticatedMonEspaceRouteImport.update({
  id: '/mon-espace',
  path: '/mon-espace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPharmacieRoute = AuthenticatedPharmacieRouteImport.update({
  id: '/pharmacie',
  path: '/pharmacie',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProRoute = AuthenticatedProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecuriteRoute = AuthenticatedSecuriteRouteImport.update({
  id: '/securite',
  path: '/securite',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CliniquesIndexRoute = CliniquesIndexRouteImport.update({
  id: '/cliniques/',
  path: '/cliniques/',
  getParentRoute: () => rootRouteImport,
} as any)
const CliniquesIdRoute = CliniquesIdRouteImport.update({
  id: '/cliniques/$id',
  path: '/cliniques/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MedecinsIndexRoute = MedecinsIndexRouteImport.update({
  id: '/medecins/',
  path: '/medecins/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedecinsIdRoute = MedecinsIdRouteImport.update({
  id: '/medecins/$id',
  path: '/medecins/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialitesIndexRoute = SpecialitesIndexRouteImport.update({
  id: '/specialites/',
  path: '/specialites/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialitesSlugRoute = SpecialitesSlugRouteImport.update({
  id: '/specialites/$slug',
  path: '/specialites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UrgenceTokenRoute = UrgenceTokenRouteImport.update({
  id: '/urgence/$token',
  path: '/urgence/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifierReferenceRoute = VerifierReferenceRouteImport.update({
  id: '/verifier/$reference',
  path: '/verifier/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetDoctorIdRoute = WidgetDoctorIdRouteImport.update({
  id: '/widget/$doctorId',
  path: '/widget/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrdonnanceIdRoute =
  AuthenticatedOrdonnanceIdRouteImport.update({
    id: '/ordonnance/$id',
    path: '/ordonnance/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaiementRetourRoute =
  AuthenticatedPaiementRetourRouteImport.update({
    id: '/paiement/retour',
    path: '/paiement/retour',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientsIdRoute = AuthenticatedPatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeleconsultationIdRoute =
  AuthenticatedTeleconsultationIdRouteImport.update({
    id: '/teleconsultation/$id',
    path: '/teleconsultation/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/aide': typeof AideRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/confirmer-email': typeof ConfirmerEmailRoute
  '/legal': typeof LegalRoute
  '/pharmacies': typeof PharmaciesRoute
  '/tarifs': typeof TarifsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/clinique': typeof AuthenticatedCliniqueRoute
  '/dossier': typeof AuthenticatedDossierRoute
  '/expertise': typeof AuthenticatedExpertiseRoute
  '/laboratoire': typeof AuthenticatedLaboratoireRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/mon-espace': typeof AuthenticatedMonEspaceRoute
  '/pharmacie': typeof AuthenticatedPharmacieRoute
  '/pro': typeof AuthenticatedProRoute
  '/securite': typeof AuthenticatedSecuriteRoute
  '/cliniques/$id': typeof CliniquesIdRoute
  '/medecins/$id': typeof MedecinsIdRoute
  '/specialites/$slug': typeof SpecialitesSlugRoute
  '/urgence/$token': typeof UrgenceTokenRoute
  '/verifier/$reference': typeof VerifierReferenceRoute
  '/widget/$doctorId': typeof WidgetDoctorIdRoute
  '/cliniques/': typeof CliniquesIndexRoute
  '/medecins/': typeof MedecinsIndexRoute
  '/specialites/': typeof SpecialitesIndexRoute
  '/ordonnance/$id': typeof AuthenticatedOrdonnanceIdRoute
  '/paiement/retour': typeof AuthenticatedPaiementRetourRoute
  '/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/teleconsultation/$id': typeof AuthenticatedTeleconsultationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/aide': typeof AideRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/confirmer-email': typeof ConfirmerEmailRoute
  '/legal': typeof LegalRoute
  '/pharmacies': typeof PharmaciesRoute
  '/tarifs': typeof TarifsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/clinique': typeof AuthenticatedCliniqueRoute
  '/dossier': typeof AuthenticatedDossierRoute
  '/expertise': typeof AuthenticatedExpertiseRoute
  '/laboratoire': typeof AuthenticatedLaboratoireRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/mon-espace': typeof AuthenticatedMonEspaceRoute
  '/pharmacie': typeof AuthenticatedPharmacieRoute
  '/pro': typeof AuthenticatedProRoute
  '/securite': typeof AuthenticatedSecuriteRoute
  '/cliniques/$id': typeof CliniquesIdRoute
  '/medecins/$id': typeof MedecinsIdRoute
  '/specialites/$slug': typeof SpecialitesSlugRoute
  '/urgence/$token': typeof UrgenceTokenRoute
  '/verifier/$reference': typeof VerifierReferenceRoute
  '/widget/$doctorId': typeof WidgetDoctorIdRoute
  '/cliniques': typeof CliniquesIndexRoute
  '/medecins': typeof MedecinsIndexRoute
  '/specialites': typeof SpecialitesIndexRoute
  '/ordonnance/$id': typeof AuthenticatedOrdonnanceIdRoute
  '/paiement/retour': typeof AuthenticatedPaiementRetourRoute
  '/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/teleconsultation/$id': typeof AuthenticatedTeleconsultationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/aide': typeof AideRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/confirmer-email': typeof ConfirmerEmailRoute
  '/legal': typeof LegalRoute
  '/pharmacies': typeof PharmaciesRoute
  '/tarifs': typeof TarifsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/clinique': typeof AuthenticatedCliniqueRoute
  '/_authenticated/dossier': typeof AuthenticatedDossierRoute
  '/_authenticated/expertise': typeof AuthenticatedExpertiseRoute
  '/_authenticated/laboratoire': typeof AuthenticatedLaboratoireRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/mon-espace': typeof AuthenticatedMonEspaceRoute
  '/_authenticated/pharmacie': typeof AuthenticatedPharmacieRoute
  '/_authenticated/pro': typeof AuthenticatedProRoute
  '/_authenticated/securite': typeof AuthenticatedSecuriteRoute
  '/cliniques/$id': typeof CliniquesIdRoute
  '/medecins/$id': typeof MedecinsIdRoute
  '/specialites/$slug': typeof SpecialitesSlugRoute
  '/urgence/$token': typeof UrgenceTokenRoute
  '/verifier/$reference': typeof VerifierReferenceRoute
  '/widget/$doctorId': typeof WidgetDoctorIdRoute
  '/cliniques/': typeof CliniquesIndexRoute
  '/medecins/': typeof MedecinsIndexRoute
  '/specialites/': typeof SpecialitesIndexRoute
  '/_authenticated/ordonnance/$id': typeof AuthenticatedOrdonnanceIdRoute
  '/_authenticated/paiement/retour': typeof AuthenticatedPaiementRetourRoute
  '/_authenticated/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/_authenticated/teleconsultation/$id': typeof AuthenticatedTeleconsultationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/aide'
    | '/assistant'
    | '/auth'
    | '/cgu'
    | '/confidentialite'
    | '/confirmer-email'
    | '/legal'
    | '/pharmacies'
    | '/tarifs'
    | '/admin'
    | '/clinique'
    | '/dossier'
    | '/expertise'
    | '/laboratoire'
    | '/messages'
    | '/mon-espace'
    | '/pharmacie'
    | '/pro'
    | '/securite'
    | '/cliniques/$id'
    | '/medecins/$id'
    | '/specialites/$slug'
    | '/urgence/$token'
    | '/verifier/$reference'
    | '/widget/$doctorId'
    | '/cliniques/'
    | '/medecins/'
    | '/specialites/'
    | '/ordonnance/$id'
    | '/paiement/retour'
    | '/patients/$id'
    | '/teleconsultation/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/aide'
    | '/assistant'
    | '/auth'
    | '/cgu'
    | '/confidentialite'
    | '/confirmer-email'
    | '/legal'
    | '/pharmacies'
    | '/tarifs'
    | '/admin'
    | '/clinique'
    | '/dossier'
    | '/expertise'
    | '/laboratoire'
    | '/messages'
    | '/mon-espace'
    | '/pharmacie'
    | '/pro'
    | '/securite'
    | '/cliniques/$id'
    | '/medecins/$id'
    | '/specialites/$slug'
    | '/urgence/$token'
    | '/verifier/$reference'
    | '/widget/$doctorId'
    | '/cliniques'
    | '/medecins'
    | '/specialites'
    | '/ordonnance/$id'
    | '/paiement/retour'
    | '/patients/$id'
    | '/teleconsultation/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$'
    | '/aide'
    | '/assistant'
    | '/auth'
    | '/cgu'
    | '/confidentialite'
    | '/confirmer-email'
    | '/legal'
    | '/pharmacies'
    | '/tarifs'
    | '/_authenticated/admin'
    | '/_authenticated/clinique'
    | '/_authenticated/dossier'
    | '/_authenticated/expertise'
    | '/_authenticated/laboratoire'
    | '/_authenticated/messages'
    | '/_authenticated/mon-espace'
    | '/_authenticated/pharmacie'
    | '/_authenticated/pro'
    | '/_authenticated/securite'
    | '/cliniques/$id'
    | '/medecins/$id'
    | '/specialites/$slug'
    | '/urgence/$token'
    | '/verifier/$reference'
    | '/widget/$doctorId'
    | '/cliniques/'
    | '/medecins/'
    | '/specialites/'
    | '/_authenticated/ordonnance/$id'
    | '/_authenticated/paiement/retour'
    | '/_authenticated/patients/$id'
    | '/_authenticated/teleconsultation/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AideRoute: typeof AideRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  CguRoute: typeof CguRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConfirmerEmailRoute: typeof ConfirmerEmailRoute
  LegalRoute: typeof LegalRoute
  PharmaciesRoute: typeof PharmaciesRoute
  TarifsRoute: typeof TarifsRoute
  CliniquesIdRoute: typeof CliniquesIdRoute
  MedecinsIdRoute: typeof MedecinsIdRoute
  SpecialitesSlugRoute: typeof SpecialitesSlugRoute
  UrgenceTokenRoute: typeof UrgenceTokenRoute
  VerifierReferenceRoute: typeof VerifierReferenceRoute
  WidgetDoctorIdRoute: typeof WidgetDoctorIdRoute
  CliniquesIndexRoute: typeof CliniquesIndexRoute
  MedecinsIndexRoute: typeof MedecinsIndexRoute
  SpecialitesIndexRoute: typeof SpecialitesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmer-email': {
      id: '/confirmer-email'
      path: '/confirmer-email'
      fullPath: '/confirmer-email'
      preLoaderRoute: typeof ConfirmerEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacies': {
      id: '/pharmacies'
      path: '/pharmacies'
      fullPath: '/pharmacies'
      preLoaderRoute: typeof PharmaciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clinique': {
      id: '/_authenticated/clinique'
      path: '/clinique'
      fullPath: '/clinique'
      preLoaderRoute: typeof AuthenticatedCliniqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dossier': {
      id: '/_authenticated/dossier'
      path: '/dossier'
      fullPath: '/dossier'
      preLoaderRoute: typeof AuthenticatedDossierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expertise': {
      id: '/_authenticated/expertise'
      path: '/expertise'
      fullPath: '/expertise'
      preLoaderRoute: typeof AuthenticatedExpertiseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laboratoire': {
      id: '/_authenticated/laboratoire'
      path: '/laboratoire'
      fullPath: '/laboratoire'
      preLoaderRoute: typeof AuthenticatedLaboratoireRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon-espace': {
      id: '/_authenticated/mon-espace'
      path: '/mon-espace'
      fullPath: '/mon-espace'
      preLoaderRoute: typeof AuthenticatedMonEspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pharmacie': {
      id: '/_authenticated/pharmacie'
      path: '/pharmacie'
      fullPath: '/pharmacie'
      preLoaderRoute: typeof AuthenticatedPharmacieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro': {
      id: '/_authenticated/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof AuthenticatedProRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/securite': {
      id: '/_authenticated/securite'
      path: '/securite'
      fullPath: '/securite'
      preLoaderRoute: typeof AuthenticatedSecuriteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/cliniques/': {
      id: '/cliniques/'
      path: '/cliniques'
      fullPath: '/cliniques/'
      preLoaderRoute: typeof CliniquesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliniques/$id': {
      id: '/cliniques/$id'
      path: '/cliniques/$id'
      fullPath: '/cliniques/$id'
      preLoaderRoute: typeof CliniquesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medecins/': {
      id: '/medecins/'
      path: '/medecins'
      fullPath: '/medecins/'
      preLoaderRoute: typeof MedecinsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medecins/$id': {
      id: '/medecins/$id'
      path: '/medecins/$id'
      fullPath: '/medecins/$id'
      preLoaderRoute: typeof MedecinsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialites/': {
      id: '/specialites/'
      path: '/specialites'
      fullPath: '/specialites/'
      preLoaderRoute: typeof SpecialitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialites/$slug': {
      id: '/specialites/$slug'
      path: '/specialites/$slug'
      fullPath: '/specialites/$slug'
      preLoaderRoute: typeof SpecialitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urgence/$token': {
      id: '/urgence/$token'
      path: '/urgence/$token'
      fullPath: '/urgence/$token'
      preLoaderRoute: typeof UrgenceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifier/$reference': {
      id: '/verifier/$reference'
      path: '/verifier/$reference'
      fullPath: '/verifier/$reference'
      preLoaderRoute: typeof VerifierReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/$doctorId': {
      id: '/widget/$doctorId'
      path: '/widget/$doctorId'
      fullPath: '/widget/$doctorId'
      preLoaderRoute: typeof WidgetDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ordonnance/$id': {
      id: '/_authenticated/ordonnance/$id'
      path: '/ordonnance/$id'
      fullPath: '/ordonnance/$id'
      preLoaderRoute: typeof AuthenticatedOrdonnanceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paiement/retour': {
      id: '/_authenticated/paiement/retour'
      path: '/paiement/retour'
      fullPath: '/paiement/retour'
      preLoaderRoute: typeof AuthenticatedPaiementRetourRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients/$id': {
      id: '/_authenticated/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof AuthenticatedPatientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teleconsultation/$id': {
      id: '/_authenticated/teleconsultation/$id'
      path: '/teleconsultation/$id'
      fullPath: '/teleconsultation/$id'
      preLoaderRoute: typeof AuthenticatedTeleconsultationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCliniqueRoute: typeof AuthenticatedCliniqueRoute
  AuthenticatedDossierRoute: typeof AuthenticatedDossierRoute
  AuthenticatedExpertiseRoute: typeof AuthenticatedExpertiseRoute
  AuthenticatedLaboratoireRoute: typeof AuthenticatedLaboratoireRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedMonEspaceRoute: typeof AuthenticatedMonEspaceRoute
  AuthenticatedPharmacieRoute: typeof AuthenticatedPharmacieRoute
  AuthenticatedProRoute: typeof AuthenticatedProRoute
  AuthenticatedSecuriteRoute: typeof AuthenticatedSecuriteRoute
  AuthenticatedOrdonnanceIdRoute: typeof AuthenticatedOrdonnanceIdRoute
  AuthenticatedPaiementRetourRoute: typeof AuthenticatedPaiementRetourRoute
  AuthenticatedPatientsIdRoute: typeof AuthenticatedPatientsIdRoute
  AuthenticatedTeleconsultationIdRoute: typeof AuthenticatedTeleconsultationIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCliniqueRoute: AuthenticatedCliniqueRoute,
  AuthenticatedDossierRoute: AuthenticatedDossierRoute,
  AuthenticatedExpertiseRoute: AuthenticatedExpertiseRoute,
  AuthenticatedLaboratoireRoute: AuthenticatedLaboratoireRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedMonEspaceRoute: AuthenticatedMonEspaceRoute,
  AuthenticatedPharmacieRoute: AuthenticatedPharmacieRoute,
  AuthenticatedProRoute: AuthenticatedProRoute,
  AuthenticatedSecuriteRoute: AuthenticatedSecuriteRoute,
  AuthenticatedOrdonnanceIdRoute: AuthenticatedOrdonnanceIdRoute,
  AuthenticatedPaiementRetourRoute: AuthenticatedPaiementRetourRoute,
  AuthenticatedPatientsIdRoute: AuthenticatedPatientsIdRoute,
  AuthenticatedTeleconsultationIdRoute: AuthenticatedTeleconsultationIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AideRoute: AideRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  CguRoute: CguRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConfirmerEmailRoute: ConfirmerEmailRoute,
  LegalRoute: LegalRoute,
  PharmaciesRoute: PharmaciesRoute,
  TarifsRoute: TarifsRoute,
  CliniquesIdRoute: CliniquesIdRoute,
  MedecinsIdRoute: MedecinsIdRoute,
  SpecialitesSlugRoute: SpecialitesSlugRoute,
  UrgenceTokenRoute: UrgenceTokenRoute,
  VerifierReferenceRoute: VerifierReferenceRoute,
  WidgetDoctorIdRoute: WidgetDoctorIdRoute,
  CliniquesIndexRoute: CliniquesIndexRoute,
  MedecinsIndexRoute: MedecinsIndexRoute,
  SpecialitesIndexRoute: SpecialitesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
