# Generated by Django 6.1.1 on 2026-09-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('login', 'Connexion'), ('login_failed', 'Échec de connexion'), ('mfa_enabled', 'Double authentification activée'), ('mfa_disabled', 'Double authentification désactivée'), ('patient_file_viewed', 'Fiche patient consultée'), ('document_viewed', 'Document consulté'), ('prescription_viewed', 'Ordonnance consultée'), ('record_written', 'Compte-rendu rédigé'), ('data_exported', 'Export des données'), ('account_deleted', 'Compte supprimé'), ('admin_verification', 'Validation (administration)'), ('payout_requested', 'Virement demandé'), ('payout_processed', 'Virement traité (administration)'), ('refund_processed', 'Remboursement effectué (administration)')], db_index=True, max_length=40),
        ),
    ]
