# Generated by Django 6.1.1 on 2026-09-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditevent_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('login', 'Connexion'), ('login_failed', 'Échec de connexion'), ('mfa_enabled', 'Double authentification activée'), ('mfa_disabled', 'Double authentification désactivée'), ('patient_file_viewed', 'Fiche patient consultée'), ('document_viewed', 'Document consulté'), ('prescription_viewed', 'Ordonnance consultée'), ('record_written', 'Compte-rendu rédigé'), ('ai_draft', "Brouillon de compte-rendu demandé à l'assistant"), ('data_exported', 'Export des données'), ('account_deleted', 'Compte supprimé'), ('admin_verification', 'Validation (administration)'), ('payout_requested', 'Virement demandé'), ('payout_processed', 'Virement traité (administration)'), ('refund_processed', 'Remboursement effectué (administration)'), ('data_export', 'Export tableur'), ('password_changed', 'Mot de passe modifié'), ('password_change_failed', 'Échec de changement de mot de passe'), ('doctor_profile_updated', 'Fiche médecin modifiée'), ('pharmacy_updated', 'Officine modifiée (pharmacien)'), ('admin_user_search', 'Recherche de compte (administration)'), ('admin_user_suspend', 'Compte suspendu (administration)'), ('admin_user_reactivate', 'Compte réactivé (administration)'), ('admin_user_reset_mfa', 'Double authentification réinitialisée (administration)'), ('admin_pharmacy_created', 'Pharmacie ajoutée (administration)'), ('admin_pharmacy_updated', 'Pharmacie modifiée (administration)'), ('admin_lab_created', 'Laboratoire ajouté (administration)'), ('admin_support_closed', "Demande d'aide traitée (administration)"), ('admin_support_reopened', "Demande d'aide rouverte (administration)")], db_index=True, max_length=40),
        ),
    ]
