# Generated by Django 6.1.1 on 2026-09-29 01:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('ussd', 'USSD')], max_length=10)),
                ('key', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('inputs', models.JSONField(default=list)),
                ('memo', models.JSONField(default=dict)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('channel', 'key'), name='bot_session_unique')],
            },
        ),
    ]
