# Generated by Django 6.1.1 on 2026-09-29 02:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0003_doctor_latitude_doctor_longitude_and_more'),
        ('medical', '0003_patientrecall_documentshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='directory.pharmacy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pharmacy', 'user'), name='pharmacy_member_unique')],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('sent', 'Envoyée'), ('preparing', 'En préparation'), ('ready', 'Prête à retirer'), ('unavailable', 'Indisponible'), ('collected', 'Retirée'), ('cancelled', 'Annulée')], default='sent', max_length=12)),
                ('patient_note', models.CharField(blank=True, max_length=300)),
                ('pharmacy_note', models.CharField(blank=True, max_length=300)),
                ('total_price', models.PositiveIntegerField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, help_text='Première consultation par la pharmacie', null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_orders', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='directory.pharmacy')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='medical.prescription')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('sent', 'preparing', 'ready'))), fields=('prescription',), name='one_open_order_per_prescription')],
            },
        ),
    ]
