# Generated by Django 6.1.1 on 2026-09-30 00:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_doctor_photo_path_pharmacy_on_duty_until_and_more'),
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.CharField(max_length=160)),
                ('note', models.CharField(blank=True, help_text='Dosage, quantité, générique accepté…', max_length=200)),
                ('expires_at', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicineAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('available', 'Disponible'), ('unavailable', 'Indisponible')], default='pending', max_length=12)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_answers', to='directory.pharmacy')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pharmacy.medicinequery')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('query', 'pharmacy'), name='unique_medicine_answer')],
            },
        ),
    ]
